"""empty message

Revision ID: 336cd5399c5f
Revises: b8c7fe083f55
Create Date: 2022-04-07 11:36:53.235567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336cd5399c5f'
down_revision = 'b8c7fe083f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_posts')
    # ### end Alembic commands ###
