"""empty message

Revision ID: 531b872a29e0
Revises: 336cd5399c5f
Create Date: 2022-04-07 11:39:53.725182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531b872a29e0'
down_revision = '336cd5399c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'blog_posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.drop_column('blog_posts', 'user_id')
    # ### end Alembic commands ###
